name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          import.env.YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          npm run build
          echo "Build completed"

      - name: List build directory
        run: ls -la dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
